% /Users/blanchette/.isabelle/contrib/zipperposition-2.1-1/x86_64-darwin/zipperposition --input tptp --output tptp --timeout 30.000 --mode=ho-pragmatic --tptp-def-as-rewrite --rewrite-before-cnf=true --max-inferences=1 --ho-unif-max-depth=1 --ho-max-elims=0 --ho-max-app-projections=0 --ho-max-rigid-imitations=1 --ho-max-identifications=0 --boolean-reasoning=bool-hoist --bool-hoist-simpl=true --bool-select=LI --recognize-injectivity=true --ext-rules=ext-family --ext-rules-max-depth=1 --ho-choice-inst=true --ho-prim-enum=none --ho-elim-leibniz=0 --interpret-bool-funs=true --try-e="$E_HOME/eprover" --tmp-dir="$ISABELLE_TMP_PREFIX" --ho-unif-level=pragmatic-framework --select=bb+e-selection2 --post-cnf-lambda-lifting=true -q "4|prefer-sos|pnrefined(2,1,1,1,2,2,2)" -q "6|prefer-processed|conjecture-relative-struct(1.5,3.5,2,3)" -q "1|const|fifo" -q "4|prefer-ground|orient-lmax(2,1,2,1,1)" -q "4|defer-sos|conjecture-relative-struct(1,5,2,3)" --avatar=off --recognize-injectivity=true --ho-neg-ext=true --e-timeout=2 --ho-pattern-decider=true --ho-fixpoint-decider=true --e-max-derived=50 --ignore-orphans=true --e-auto=true --presaturate=true --e-call-point=0.1 /Users/blanchette/.isabelle/prob_zipperposition_1.p
% This file was generated by Isabelle (most likely Sledgehammer)
% 2022-06-15 17:04:31.979

% Explicit typings (3)
thf(sy_c_DPE_Op, type,
    p : !>[A : $tType, B : $tType]: (A > B > $o)).
thf(sy_c_DPE_Oq, type,
    q : !>[A : $tType]: (A > $o)).
thf(sy_c_DPE_Or, type,
    r : !>[A : $tType]: (A > $o)).

% Relevant facts (3)
thf(fact_0_assms__6_I3_J, axiom,
    ((![E : $tType, F : $tType]: (![X : E, Y : F, E2 : $o]: ((p @ (E) @ (F) @ X @ Y) | ((r @ (F) @ Y) != E2)))))). % assms_6(3)
thf(fact_1_assms__6_I2_J, axiom,
    ((![D : $tType, C : $tType]: (![X : C, Y : D, E2 : $o]: ((p @ (C) @ (D) @ X @ Y) | ((q @ (C) @ X) != E2)))))). % assms_6(2)
thf(fact_2_assms__6_I1_J, axiom,
    ((![A : $tType, B : $tType]: (![X : A, Y : B, E2 : $o]: ((~ ((p @ (A) @ (B) @ X @ Y))) | (((q @ (A) @ X) = E2) | ((r @ (B) @ Y) = E2))))))). % assms_6(1)

% Conjectures (1)
thf(conj_0, conjecture,
    (($false))).
