% /Users/blanchette/.isabelle/contrib/zipperposition-2.1-1/x86_64-darwin/zipperposition --input tptp --output tptp --timeout 30.000 --mode=ho-pragmatic --tptp-def-as-rewrite --rewrite-before-cnf=true --max-inferences=1 --ho-unif-max-depth=1 --ho-max-elims=0 --ho-max-app-projections=0 --ho-max-rigid-imitations=1 --ho-max-identifications=0 --boolean-reasoning=bool-hoist --bool-hoist-simpl=true --bool-select=LI --recognize-injectivity=true --ext-rules=ext-family --ext-rules-max-depth=1 --ho-choice-inst=true --ho-prim-enum=none --ho-elim-leibniz=0 --interpret-bool-funs=true --try-e="$E_HOME/eprover" --tmp-dir="$ISABELLE_TMP_PREFIX" --ho-unif-level=pragmatic-framework --select=bb+e-selection2 --post-cnf-lambda-lifting=true -q "4|prefer-sos|pnrefined(2,1,1,1,2,2,2)" -q "6|prefer-processed|conjecture-relative-struct(1.5,3.5,2,3)" -q "1|const|fifo" -q "4|prefer-ground|orient-lmax(2,1,2,1,1)" -q "4|defer-sos|conjecture-relative-struct(1,5,2,3)" --avatar=off --recognize-injectivity=true --ho-neg-ext=true --e-timeout=2 --ho-pattern-decider=true --ho-fixpoint-decider=true --e-max-derived=50 --ignore-orphans=true --e-auto=true --presaturate=true --e-call-point=0.1 /Users/blanchette/.isabelle/prob_zipperposition_1.p
% This file was generated by Isabelle (most likely Sledgehammer)
% 2022-05-13 14:04:23.544

% Could-be-implicit typings (4)
thf(ty_t_Product__Type_Oprod, type,
    product_prod : $tType > $tType > $tType).
thf(ty_t_Option_Ooption, type,
    option : $tType > $tType).
thf(ty_t_List_Olist, type,
    list : $tType > $tType).
thf(ty_t_Nat_Onat, type,
    nat : $tType).

% Explicit typings (5)
thf(sy_c_DPE_Oa, type,
    a : !>[A : $tType]: A).
thf(sy_c_DPE_Ob, type,
    b : !>[A : $tType]: A).
thf(sy_c_DPE_Op, type,
    p : !>[A : $tType, B : $tType]: (A > B > $o)).
thf(sy_c_DPE_Oq, type,
    q : !>[A : $tType]: (A > $o)).
thf(sy_c_DPE_Or, type,
    r : !>[A : $tType]: (A > $o)).

% Relevant facts (5)
thf(fact_0_assms__10_I5_J, axiom,
    ((![K : $tType]: ((a @ (K)) = (b @ (K)))))). % assms_10(5)
thf(fact_1_assms__10_I4_J, axiom,
    ((![J : $tType, A : $tType, B : $tType, C : $tType]: (![C2 : (product_prod @ B @ (list @ C)), D : nat]: ((p @ ((option @ A)) @ (J) @ (a @ ((option @ A))) @ (b @ (J))) | (~ ((p @ ((product_prod @ B @ (list @ C))) @ (nat) @ C2 @ D)))))))). % assms_10(4)
thf(fact_2_assms__10_I3_J, axiom,
    ((![H : $tType, I : $tType]: (![X : H, Y : I]: ((p @ (H) @ (I) @ X @ Y) | (~ ((r @ (I) @ Y)))))))). % assms_10(3)
thf(fact_3_assms__10_I2_J, axiom,
    ((![G : $tType, F : $tType]: (![X : F, Y : G]: ((p @ (F) @ (G) @ X @ Y) | (~ ((q @ (F) @ X)))))))). % assms_10(2)
thf(fact_4_assms__10_I1_J, axiom,
    ((![D2 : $tType, E : $tType]: (![X : D2, Y : E]: ((~ ((p @ (D2) @ (E) @ X @ Y))) | ((q @ (D2) @ X) | (r @ (E) @ Y))))))). % assms_10(1)

% Conjectures (1)
thf(conj_0, conjecture,
    (($false))).
