% /Users/blanchette/.isabelle/contrib/zipperposition-2.1-1/x86_64-darwin/zipperposition --input tptp --output tptp --timeout 30.000 --mode=ho-pragmatic --tptp-def-as-rewrite --rewrite-before-cnf=true --max-inferences=1 --ho-unif-max-depth=1 --ho-max-elims=0 --ho-max-app-projections=0 --ho-max-rigid-imitations=1 --ho-max-identifications=0 --boolean-reasoning=bool-hoist --bool-hoist-simpl=true --bool-select=LI --recognize-injectivity=true --ext-rules=ext-family --ext-rules-max-depth=1 --ho-choice-inst=true --ho-prim-enum=none --ho-elim-leibniz=0 --interpret-bool-funs=true --try-e="$E_HOME/eprover" --tmp-dir="$ISABELLE_TMP_PREFIX" --ho-unif-level=pragmatic-framework --select=bb+e-selection2 --post-cnf-lambda-lifting=true -q "4|prefer-sos|pnrefined(2,1,1,1,2,2,2)" -q "6|prefer-processed|conjecture-relative-struct(1.5,3.5,2,3)" -q "1|const|fifo" -q "4|prefer-ground|orient-lmax(2,1,2,1,1)" -q "4|defer-sos|conjecture-relative-struct(1,5,2,3)" --avatar=off --recognize-injectivity=true --ho-neg-ext=true --e-timeout=2 --ho-pattern-decider=true --ho-fixpoint-decider=true --e-max-derived=50 --ignore-orphans=true --e-auto=true --presaturate=true --e-call-point=0.1 /Users/blanchette/.isabelle/prob_zipperposition_1.p
% This file was generated by Isabelle (most likely Sledgehammer)
% 2022-06-15 17:16:54.693

% Could-be-implicit typings (7)
thf(ty_n_tf__g, type,
    g : $tType).
thf(ty_n_tf__f, type,
    f : $tType).
thf(ty_n_tf__e, type,
    e : $tType).
thf(ty_n_tf__d, type,
    d : $tType).
thf(ty_n_tf__c, type,
    c : $tType).
thf(ty_n_tf__b, type,
    b : $tType).
thf(ty_n_tf__a, type,
    a : $tType).

% Explicit typings (10)
thf(sy_c_DPE_Oe_001tf__d, type,
    e_d : d).
thf(sy_c_DPE_Oe_001tf__f, type,
    e_f : f).
thf(sy_c_DPE_Oe_001tf__g, type,
    e_g : g).
thf(sy_v_a, type,
    a2 : c).
thf(sy_v_b, type,
    b2 : c > $o).
thf(sy_v_c, type,
    c2 : c > $o).
thf(sy_v_f, type,
    f2 : a > a > b).
thf(sy_v_p, type,
    p : (a > b) > (c > $o) > $o).
thf(sy_v_q, type,
    q : (((a > b) > e) > e) > d).
thf(sy_v_r, type,
    r : (c > $o) > f).

% Relevant facts (6)
thf(fact_0_assms_I6_J, axiom,
    ((b2 = c2))). % assms(6)
thf(fact_1_assms_I5_J, axiom,
    ((![Z : g > $o]: ((Z @ e_g) | (p @ (^[X : a]: (f2 @ X @ X)) @ b2))))). % assms(5)
thf(fact_2_assms_I4_J, axiom,
    ((![X2 : a > b, Y : c > $o]: ((p @ X2 @ Y) | (~ ((Y @ a2))))))). % assms(4)
thf(fact_3_assms_I3_J, axiom,
    ((![X2 : a > b, Y : c > $o]: ((p @ X2 @ Y) | ((r @ Y) != e_f))))). % assms(3)
thf(fact_4_assms_I2_J, axiom,
    ((![X2 : a > b, Y : c > $o]: ((p @ X2 @ Y) | ((q @ (^[Y2 : (a > b) > e]: (Y2 @ X2))) != e_d))))). % assms(2)
thf(fact_5_assms_I1_J, axiom,
    ((![X2 : a > b, Y : c > $o]: ((~ ((p @ X2 @ Y))) | (((q @ (^[Y2 : (a > b) > e]: (Y2 @ X2))) = e_d) | (((r @ Y) = e_f) | (Y @ a2))))))). % assms(1)

% Conjectures (1)
thf(conj_0, conjecture,
    (($false))).
