% /Users/blanchette/.isabelle/contrib/zipperposition-2.1-1/x86_64-darwin/zipperposition --input tptp --output tptp --timeout 30.000 --mode=ho-pragmatic --tptp-def-as-rewrite --rewrite-before-cnf=true --max-inferences=1 --ho-unif-max-depth=1 --ho-max-elims=0 --ho-max-app-projections=0 --ho-max-rigid-imitations=1 --ho-max-identifications=0 --boolean-reasoning=bool-hoist --bool-hoist-simpl=true --bool-select=LI --recognize-injectivity=true --ext-rules=ext-family --ext-rules-max-depth=1 --ho-choice-inst=true --ho-prim-enum=none --ho-elim-leibniz=0 --interpret-bool-funs=true --try-e="$E_HOME/eprover" --tmp-dir="$ISABELLE_TMP_PREFIX" --ho-unif-level=pragmatic-framework --select=bb+e-selection2 --post-cnf-lambda-lifting=true -q "4|prefer-sos|pnrefined(2,1,1,1,2,2,2)" -q "6|prefer-processed|conjecture-relative-struct(1.5,3.5,2,3)" -q "1|const|fifo" -q "4|prefer-ground|orient-lmax(2,1,2,1,1)" -q "4|defer-sos|conjecture-relative-struct(1,5,2,3)" --avatar=off --recognize-injectivity=true --ho-neg-ext=true --e-timeout=2 --ho-pattern-decider=true --ho-fixpoint-decider=true --e-max-derived=50 --ignore-orphans=true --e-auto=true --presaturate=true --e-call-point=0.1 /Users/blanchette/.isabelle/prob_zipperposition_1.p
% This file was generated by Isabelle (most likely Sledgehammer)
% 2022-07-11 16:15:38.474

% Could-be-implicit typings (9)
thf(ty_tf_i, type,
    i : $tType).
thf(ty_tf_h, type,
    h : $tType).
thf(ty_tf_g, type,
    g : $tType).
thf(ty_tf_f, type,
    f : $tType).
thf(ty_tf_e, type,
    e : $tType).
thf(ty_tf_d, type,
    d : $tType).
thf(ty_tf_c, type,
    c : $tType).
thf(ty_tf_b, type,
    b : $tType).
thf(ty_tf_a, type,
    a : $tType).

% Explicit typings (10)
thf(sy_c_DPE_Oa, type,
    a2 : !>[A : $tType]: A).
thf(sy_c_DPE_Ob, type,
    b2 : !>[A : $tType]: A).
thf(sy_c_DPE_Oe, type,
    e2 : !>[A : $tType]: A).
thf(sy_c_DPE_Op, type,
    p : !>[A : $tType, B : $tType]: (A > B > $o)).
thf(sy_c_DPE_Oq, type,
    q : !>[A : $tType]: (A > A)).
thf(sy_c_DPE_Or, type,
    r : !>[A : $tType]: (A > A)).
thf(sy_v_c, type,
    c2 : i).
thf(sy_v_s, type,
    s : (b > c > $o) > a).
thf(sy_v_t, type,
    t : (e > $o) > d).
thf(sy_v_u, type,
    u : $o > g).

% Relevant facts (6)
thf(fact_0_assms__24_I6_J, axiom,
    ((![O : $tType]: (![C : O]: ((b2 @ (O)) = C))))). % assms_24(6)
thf(fact_1_assms__24_I5_J, axiom,
    ((![K : $tType, L : $tType, M : $tType, N : $tType]: (![Z : K > $o, F : L > L > M]: ((Z @ (e2 @ (K))) | (p @ (L > M) @ (N) @ (^[X : L]: (F @ X @ X)) @ (b2 @ (N)))))))). % assms_24(5)
thf(fact_2_assms__24_I4_J, axiom,
    ((![I : $tType, J : $tType]: (![X2 : I, Y : J > $o]: ((p @ (I) @ (J > $o) @ X2 @ Y) | (~ ((Y @ (a2 @ (J)))))))))). % assms_24(4)
thf(fact_3_assms__24_I3_J, axiom,
    ((![G : $tType, H : $tType]: (![X2 : G, Y : H]: ((p @ (G) @ (H) @ X2 @ Y) | ((r @ (H) @ Y) != (e2 @ (H)))))))). % assms_24(3)
thf(fact_4_assms__24_I2_J, axiom,
    ((![E : $tType, F2 : $tType, D : $tType]: (![X2 : D, Y : E]: ((p @ (D) @ (E) @ X2 @ Y) | ((q @ ((D > F2) > F2) @ (^[Y2 : D > F2]: (Y2 @ X2))) != (e2 @ ((D > F2) > F2)))))))). % assms_24(2)
thf(fact_5_assms__24_I1_J, axiom,
    ((![C2 : $tType, A : $tType, B : $tType]: (![X2 : A, Y : B > $o]: ((~ ((p @ (A) @ (B > $o) @ X2 @ Y))) | (((q @ ((A > C2) > C2) @ (^[Y2 : A > C2]: (Y2 @ X2))) = (e2 @ ((A > C2) > C2))) | (((r @ (B > $o) @ Y) = (e2 @ (B > $o))) | (Y @ (a2 @ (B)))))))))). % assms_24(1)

% Conjectures (1)
thf(conj_0, conjecture,
    ((((s @ (p @ (b) @ (c))) = (e2 @ (a))) & (((t @ (p @ (f) @ (e) @ (a2 @ (f)))) = (e2 @ (d))) & ((u @ (p @ (h) @ (i) @ (a2 @ (h)) @ c2)) = (e2 @ (g))))))).
