% /Users/blanchette/.isabelle/contrib/zipperposition-2.1-1/x86_64-darwin/zipperposition --input tptp --output tptp --timeout 30.000 --mode=ho-pragmatic --tptp-def-as-rewrite --rewrite-before-cnf=true --max-inferences=1 --ho-unif-max-depth=1 --ho-max-elims=0 --ho-max-app-projections=0 --ho-max-rigid-imitations=1 --ho-max-identifications=0 --boolean-reasoning=bool-hoist --bool-hoist-simpl=true --bool-select=LI --recognize-injectivity=true --ext-rules=ext-family --ext-rules-max-depth=1 --ho-choice-inst=true --ho-prim-enum=none --ho-elim-leibniz=0 --interpret-bool-funs=true --try-e="$E_HOME/eprover" --tmp-dir="$ISABELLE_TMP_PREFIX" --ho-unif-level=pragmatic-framework --select=bb+e-selection2 --post-cnf-lambda-lifting=true -q "4|prefer-sos|pnrefined(2,1,1,1,2,2,2)" -q "6|prefer-processed|conjecture-relative-struct(1.5,3.5,2,3)" -q "1|const|fifo" -q "4|prefer-ground|orient-lmax(2,1,2,1,1)" -q "4|defer-sos|conjecture-relative-struct(1,5,2,3)" --avatar=off --recognize-injectivity=true --ho-neg-ext=true --e-timeout=2 --ho-pattern-decider=true --ho-fixpoint-decider=true --e-max-derived=50 --ignore-orphans=true --e-auto=true --presaturate=true --e-call-point=0.1 /Users/blanchette/.isabelle/prob_zipperposition_1.p
% This file was generated by Isabelle (most likely Sledgehammer)
% 2022-05-04 11:51:49.467

% Could-be-implicit typings (4)
thf(ty_t_Product__Type_Ounit, type,
    product_unit : $tType).
thf(ty_t_Product__Type_Oprod, type,
    product_prod : $tType > $tType > $tType).
thf(ty_t_Nat_Onat, type,
    nat : $tType).
thf(ty_t_Int_Oint, type,
    int : $tType).

% Explicit typings (6)
thf(sy_c_PE_Op, type,
    p : !>[A : $tType]: (A > $o)).
thf(sy_c_PE_Oq, type,
    q : !>[A : $tType]: (A > $o)).
thf(sy_c_PE_Ou, type,
    u : !>[A : $tType]: A).
thf(sy_c_PE_Ov, type,
    v : !>[A : $tType]: A).
thf(sy_c_PE_Ow, type,
    w : !>[A : $tType]: A).
thf(sy_c_PE_Ox, type,
    x : !>[A : $tType]: A).

% Relevant facts (6)
thf(fact_0_assms__8_I6_J, axiom,
    ((~ ((q @ (int) @ (w @ (int))))))). % assms_8(6)
thf(fact_1_assms__8_I5_J, axiom,
    ((~ ((q @ (product_unit) @ (v @ (product_unit))))))). % assms_8(5)
thf(fact_2_assms__8_I4_J, axiom,
    ((~ ((q @ (product_unit) @ (u @ (product_unit))))))). % assms_8(4)
thf(fact_3_assms__8_I3_J, axiom,
    ((![A : $tType]: (q @ (A) @ (x @ (A)))))). % assms_8(3)
thf(fact_4_assms__8_I2_J, axiom,
    ((![A : $tType]: ((~ ((p @ ((product_prod @ nat @ A)) @ (x @ ((product_prod @ nat @ A)))))) | (q @ (A) @ (w @ (A))))))). % assms_8(2)
thf(fact_5_assms__8_I1_J, axiom,
    ((![A : $tType]: ((q @ (A) @ (u @ (A))) | ((q @ (A) @ (v @ (A))) | (p @ ((product_prod @ A @ int)) @ (x @ ((product_prod @ A @ int))))))))). % assms_8(1)

% Conjectures (1)
thf(conj_0, conjecture,
    (($false))).
