% /Users/blanchette/.isabelle/contrib/zipperposition-2.1-1/x86_64-darwin/zipperposition --input tptp --output tptp --timeout 30.000 --mode=ho-pragmatic --tptp-def-as-rewrite --rewrite-before-cnf=true --max-inferences=1 --ho-unif-max-depth=1 --ho-max-elims=0 --ho-max-app-projections=0 --ho-max-rigid-imitations=1 --ho-max-identifications=0 --boolean-reasoning=bool-hoist --bool-hoist-simpl=true --bool-select=LI --recognize-injectivity=true --ext-rules=ext-family --ext-rules-max-depth=1 --ho-choice-inst=true --ho-prim-enum=none --ho-elim-leibniz=0 --interpret-bool-funs=true --try-e="$E_HOME/eprover" --tmp-dir="$ISABELLE_TMP_PREFIX" --ho-unif-level=pragmatic-framework --select=bb+e-selection2 --post-cnf-lambda-lifting=true -q "4|prefer-sos|pnrefined(2,1,1,1,2,2,2)" -q "6|prefer-processed|conjecture-relative-struct(1.5,3.5,2,3)" -q "1|const|fifo" -q "4|prefer-ground|orient-lmax(2,1,2,1,1)" -q "4|defer-sos|conjecture-relative-struct(1,5,2,3)" --avatar=off --recognize-injectivity=true --ho-neg-ext=true --e-timeout=2 --ho-pattern-decider=true --ho-fixpoint-decider=true --e-max-derived=50 --ignore-orphans=true --e-auto=true --presaturate=true --e-call-point=0.1 /Users/blanchette/.isabelle/prob_zipperposition_1.p
% This file was generated by Isabelle (most likely Sledgehammer)
% 2022-05-13 13:48:07.721

% Explicit typings (2)
thf(sy_c_SPE_Of, type,
    f : !>[A : $tType]: (A > A)).
thf(sy_c_SPE_Op, type,
    p : !>[A : $tType]: (A > $o)).

% Relevant facts (5)
thf(fact_0_assms__12_I5_J, axiom,
    ((![A : $tType]: (![Two : A, Five : A, Six : A]: ((~ ((p @ (A) @ Two))) | ((f @ (A) @ Five) = Six)))))). % assms_12(5)
thf(fact_1_assms__12_I4_J, axiom,
    ((![A : $tType]: (![One : A, Four : A, Five : A]: ((~ ((p @ (A) @ One))) | ((f @ (A) @ Four) = Five)))))). % assms_12(4)
thf(fact_2_assms__12_I3_J, axiom,
    ((![A : $tType]: (![Three : A, Four : A]: ((p @ (A) @ Three) | ((f @ (A) @ Three) = Four)))))). % assms_12(3)
thf(fact_3_assms__12_I2_J, axiom,
    ((![A : $tType]: (![Two : A, Three : A]: ((p @ (A) @ Two) | ((f @ (A) @ Two) = Three)))))). % assms_12(2)
thf(fact_4_assms__12_I1_J, axiom,
    ((![A : $tType]: (![One : A, Two : A]: ((p @ (A) @ One) | ((f @ (A) @ One) = Two)))))). % assms_12(1)

% Conjectures (1)
thf(conj_0, conjecture,
    (($false))).
