; main lib

(rule
 (targets builtin_gen.ml builtin_gen.mli)
 (deps gen_builtin.ml)
 (action
  (run ocaml %{project_root}/src/core/gen_builtin.ml %{targets})))

(library
 (name logtk)
 (public_name logtk)
 (synopsis "core data structures and algorithms for Logtk")
 (libraries
  containers
  containers-data
  iter
  oseq
  unix
  mtime
  mtime.clock.os
  atomic
  logtk.common
  logtk.arith
  logtk.hash
  zipperposition_mdag)
 (flags :standard -w -27-32-50 -open Logtk_arith -open Logtk_common)
 (foreign_stubs
  (language c)
  (names util_stubs)
  (flags :standard -Wextra -Wno-unused-parameter)))

(documentation
 (package logtk))
