% TIMEFORMAT='%3R'; { time (exec 2>&1; '/usr/local/bin/zipperposition' -print none -proof tstp -print-types -timeout 30 '/home/mathias/.isabelle/prob_zipperposition_1' ) ; }
% This file was generated by Isabelle (most likely Sledgehammer)
% 2014-05-05 18:02:48.184

% Could-be-implicit typings (4)
tff(ty_t_List_Olist, type,
    list_ : $tType > $tType).
tff(ty_t_HOL_Obool, type,
    bool_ : $tType).
tff(ty_t_Num_Onum, type,
    num_ : $tType).
tff(ty_t_Int_Oint, type,
    int_ : $tType).

% Explicit typings (11)
tff(sy_cl_Nat_Osemiring__char__0, type,
    semiring_char_0_ : !>[A : $tType]: $o).
tff(sy_c_Groups_Oone__class_Oone, type,
    one_one_ : !>[A : $tType]: A).
tff(sy_c_List_Olist_OCons, type,
    cons_ : !>[A : $tType]: ((A * list_(A)) > list_(A))).
tff(sy_c_List_Olist_ONil, type,
    nil_ : !>[A : $tType]: list_(A)).
tff(sy_c_List_Orev, type,
    rev_ : !>[A : $tType]: (list_(A) > list_(A))).
tff(sy_c_Num_Onum_OBit0, type,
    bit0_ : num_ > num_).
tff(sy_c_Num_Onum_OOne, type,
    one_ : num_).
tff(sy_c_Num_Onumeral__class_Onumeral, type,
    numeral_numeral_ : !>[A : $tType]: (num_ > A)).
tff(sy_c_fFalse, type,
    fFalse_ : bool_).
tff(sy_c_fTrue, type,
    fTrue_ : bool_).
tff(sy_c_pp, type,
    pp_ : bool_ > $o).

% Relevant facts (5)
tff(fact_0_list_Oinject, axiom, % list.inject
    ((![A : $tType]: (![X21 : A, X22 : list_(A), Y21 : A, Y22 : list_(A)]: (cons_(A, X21, X22) = cons_(A, Y21, Y22) <=> (X21 = Y21 & X22 = Y22)))))).
tff(fact_1_numeral__eq__iff, axiom, % numeral_eq_iff
    ((![A : $tType]: (semiring_char_0_(A) => (![M : num_, N : num_]: (numeral_numeral_(A, M) = numeral_numeral_(A, N) <=> M = N)))))).
tff(fact_2_list_Oexhaust, axiom, % list.exhaust
    ((![A : $tType]: (![Y : list_(A)]: ((~ Y = nil_(A)) => (~ (![X212 : A, X222 : list_(A)]: (~ Y = cons_(A, X212, X222))))))))).
tff(fact_3_list_Odistinct_I1_J, axiom, % list.distinct(1)
    ((![A : $tType]: (![X21 : A, X22 : list_(A)]: (~ nil_(A) = cons_(A, X21, X22)))))).
tff(fact_4_neq__Nil__conv, axiom, % neq_Nil_conv
    ((![A : $tType]: (![Xs : list_(A)]: ((~ Xs = nil_(A)) <=> (?[Y2 : A, Ys : list_(A)]: Xs = cons_(A, Y2, Ys))))))).

% Type constructors (1)
tff(tcon_Int_Oint___Nat_Osemiring__char__0, axiom,
    (semiring_char_0_(int_))).

% Helper facts (2)
tff(help_pp_2_1_U, axiom,
    (pp_(fTrue_))).
tff(help_pp_1_1_U, axiom,
    ((~ pp_(fFalse_)))).

% Conjectures (1)
tff(conj_0, conjecture,
    (rev_(int_, cons_(int_, one_one_(int_), cons_(int_, numeral_numeral_(int_, bit0_(one_)), nil_(int_)))) = cons_(int_, numeral_numeral_(int_, bit0_(one_)), cons_(int_, one_one_(int_), nil_(int_))))).
