% TIMEFORMAT='%3R'; { time (exec 2>&1; '/usr/local/bin/zipperposition' -print none -proof tstp -print-types -timeout 30 '/home/mathias/.isabelle/prob_zipperposition_1' ) ; }
% This file was generated by Isabelle (most likely Sledgehammer)
% 2014-05-07 11:31:14.211

% Could-be-implicit typings (6)
tff(ty_t_List_Olist, type,
    list_ : $tType > $tType).
tff(ty_t_HOL_Obool, type,
    bool_ : $tType).
tff(ty_t_Num_Onum, type,
    num_ : $tType).
tff(ty_t_Nat_Onat, type,
    nat_ : $tType).
tff(ty_t_Int_Oint, type,
    int_ : $tType).
tff(ty_t_fun, type,
    fun_ : ($tType * $tType) > $tType).

% Explicit typings (34)
tff(sy_cl_Groups_Oone, type,
    one_ : !>[A : $tType]: $o).
tff(sy_cl_Num_Onumeral, type,
    numeral_ : !>[A : $tType]: $o).
tff(sy_cl_Groups_Ouminus, type,
    uminus_ : !>[A : $tType]: $o).
tff(sy_cl_Num_Oneg__numeral, type,
    neg_numeral_ : !>[A : $tType]: $o).
tff(sy_cl_Num_Oring__char__0, type,
    ring_char_0_ : !>[A : $tType]: $o).
tff(sy_cl_Groups_Ogroup__add, type,
    group_add_ : !>[A : $tType]: $o).
tff(sy_cl_Groups_Oab__group__add, type,
    ab_group_add_ : !>[A : $tType]: $o).
tff(sy_cl_Nat_Osemiring__char__0, type,
    semiring_char_0_ : !>[A : $tType]: $o).
tff(sy_cl_Groups_Osemigroup__add, type,
    semigroup_add_ : !>[A : $tType]: $o).
tff(sy_cl_Groups_Oab__semigroup__add, type,
    ab_semigroup_add_ : !>[A : $tType]: $o).
tff(sy_cl_Groups_Ocancel__semigroup__add, type,
    cancel_semigroup_add_ : !>[A : $tType]: $o).
tff(sy_cl_Groups_Ocancel__ab__semigroup__add, type,
    cancel146912293up_add_ : !>[A : $tType]: $o).
tff(sy_cl_Groups_Oordered__ab__semigroup__add, type,
    ordere779506340up_add_ : !>[A : $tType]: $o).
tff(sy_c_Groups_Oone__class_Oone, type,
    one_one_ : !>[A : $tType]: A).
tff(sy_c_Groups_Oplus__class_Oplus, type,
    plus_plus_ : !>[A : $tType]: ((A * A) > A)).
tff(sy_c_Groups_Ouminus__class_Ouminus, type,
    uminus_uminus_ : !>[A : $tType]: (A > A)).
tff(sy_c_List_Obind, type,
    bind_ : !>[A : $tType, B : $tType]: ((list_(A) * fun_(A, list_(B))) > list_(B))).
tff(sy_c_List_Oinsert, type,
    insert_ : !>[A : $tType]: ((A * list_(A)) > list_(A))).
tff(sy_c_List_Olist_OCons, type,
    cons_ : !>[A : $tType]: ((A * list_(A)) > list_(A))).
tff(sy_c_List_Olist_ONil, type,
    nil_ : !>[A : $tType]: list_(A)).
tff(sy_c_List_Olist__ex1, type,
    list_ex1_ : !>[A : $tType]: ((fun_(A, bool_) * list_(A)) > $o)).
tff(sy_c_List_Oproduct__lists, type,
    product_lists_ : !>[A : $tType]: (list_(list_(A)) > list_(list_(A)))).
tff(sy_c_List_Orev, type,
    rev_ : !>[A : $tType]: (list_(A) > list_(A))).
tff(sy_c_List_Osublists, type,
    sublists_ : !>[A : $tType]: (list_(A) > list_(list_(A)))).
tff(sy_c_Nat_OSuc, type,
    suc_ : nat_ > nat_).
tff(sy_c_Num_Oneg__numeral__class_Odbl, type,
    neg_numeral_dbl_ : !>[A : $tType]: (A > A)).
tff(sy_c_Num_Onum_OBit0, type,
    bit0_ : num_ > num_).
tff(sy_c_Num_Onum_OOne, type,
    one_2 : num_).
tff(sy_c_Num_Onum_Ocase__num, type,
    case_num_ : !>[T : $tType]: ((T * fun_(num_, T) * fun_(num_, T) * num_) > T)).
tff(sy_c_Num_Onumeral__class_Onumeral, type,
    numeral_numeral_ : !>[A : $tType]: (num_ > A)).
tff(sy_c_aa, type,
    aa_ : !>[A : $tType, B : $tType]: ((fun_(A, B) * A) > B)).
tff(sy_c_fFalse, type,
    fFalse_ : bool_).
tff(sy_c_fTrue, type,
    fTrue_ : bool_).
tff(sy_c_pp, type,
    pp_ : bool_ > $o).

% Relevant facts (94)

tff(fact_6_semiring__norm_I85_J, axiom, % semiring_norm(85)
    ((![M : num_]: (~ bit0_(M) = one_2)))).
tff(fact_13_numeral__eq__iff, axiom, % numeral_eq_iff
    ((![A : $tType]: (semiring_char_0_(A) => (![M : num_, N : num_]: (numeral_numeral_(A, M) = numeral_numeral_(A, N) <=> M = N)))))).

tff(fact_36_add__left__cancel, axiom, % add_left_cancel
    ((![A : $tType]: (cancel_semigroup_add_(A) => (![A2 : A, B2 : A, C : A]: (plus_plus_(A, A2, B2) = plus_plus_(A, A2, C) <=> B2 = C)))))).

tff(fact_90_Suc__eq__plus1, axiom, % Suc_eq_plus1
    ((![N : nat_]: suc_(N) = plus_plus_(nat_, N, one_one_(nat_))))).
tff(fact_91_Suc__eq__plus1__left, axiom, % Suc_eq_plus1_left
    ((![N : nat_]: suc_(N) = plus_plus_(nat_, one_one_(nat_), N)))).

% Type constructors (22)
tff(tcon_Int_Oint___Groups_Oordered__ab__semigroup__add, axiom,
    (ordere779506340up_add_(int_))).
tff(tcon_Int_Oint___Groups_Ocancel__ab__semigroup__add, axiom,
    (cancel146912293up_add_(int_))).
tff(tcon_Int_Oint___Groups_Ocancel__semigroup__add, axiom,
    (cancel_semigroup_add_(int_))).
tff(tcon_Int_Oint___Groups_Oab__semigroup__add, axiom,
    (ab_semigroup_add_(int_))).
tff(tcon_Int_Oint___Groups_Osemigroup__add, axiom,
    (semigroup_add_(int_))).
tff(tcon_Int_Oint___Nat_Osemiring__char__0, axiom,
    (semiring_char_0_(int_))).
tff(tcon_Int_Oint___Groups_Oab__group__add, axiom,
    (ab_group_add_(int_))).
tff(tcon_Int_Oint___Groups_Ogroup__add, axiom,
    (group_add_(int_))).
tff(tcon_Int_Oint___Num_Oring__char__0, axiom,
    (ring_char_0_(int_))).
tff(tcon_Int_Oint___Num_Oneg__numeral, axiom,
    (neg_numeral_(int_))).
tff(tcon_Int_Oint___Groups_Ouminus, axiom,
    (uminus_(int_))).
tff(tcon_Int_Oint___Num_Onumeral, axiom,
    (numeral_(int_))).
tff(tcon_Int_Oint___Groups_Oone, axiom,
    (one_(int_))).
tff(tcon_Nat_Onat___Groups_Oordered__ab__semigroup__add_1, axiom,
    (ordere779506340up_add_(nat_))).
tff(tcon_Nat_Onat___Groups_Ocancel__ab__semigroup__add_2, axiom,
    (cancel146912293up_add_(nat_))).
tff(tcon_Nat_Onat___Groups_Ocancel__semigroup__add_3, axiom,
    (cancel_semigroup_add_(nat_))).
tff(tcon_Nat_Onat___Groups_Oab__semigroup__add_4, axiom,
    (ab_semigroup_add_(nat_))).
tff(tcon_Nat_Onat___Groups_Osemigroup__add_5, axiom,
    (semigroup_add_(nat_))).
tff(tcon_Nat_Onat___Nat_Osemiring__char__0_6, axiom,
    (semiring_char_0_(nat_))).
tff(tcon_Nat_Onat___Num_Onumeral_7, axiom,
    (numeral_(nat_))).
tff(tcon_Nat_Onat___Groups_Oone_8, axiom,
    (one_(nat_))).
tff(tcon_HOL_Obool___Groups_Ouminus_9, axiom,
    (uminus_(bool_))).

% Helper facts (2)
tff(help_pp_2_1_U, axiom,
    (pp_(fTrue_))).
tff(help_pp_1_1_U, axiom,
    ((~ pp_(fFalse_)))).

% Conjectures (1)
tff(conj_0, conjecture,
    (rev_(int_, cons_(int_, one_one_(int_), cons_(int_, numeral_numeral_(int_, bit0_(bit0_(one_2))), nil_(int_)))) = cons_(int_, numeral_numeral_(int_, bit0_(bit0_(one_2))), cons_(int_, one_one_(int_), nil_(int_))))).
