(env
 (_
  (flags
   :standard
   -warn-error
   +a-3-8-27-32-50-69
   -w
   -3-26-32-33-34-37-38-50-67
   -color
   always
   -safe-string)
  (ocamlopt_flags :standard -O3 -unbox-closures -unbox-closures-factor 20)))

(rule
 (alias runtest)
 (package zipperposition)
 (locks /tlock)
 (enabled_if
  (= %{ocaml-config:os_type} Unix))
 (deps
  main/zipperposition.exe
  test_must_pass.sh
  (source_tree ../examples/))
 (action
  (run ./test_must_pass.sh ./main/zipperposition.exe)))

;(documentation
;  (package logtk))
